train:
  seed: 0
  gpu: 0
  model_path:
  export_path: './outputs'
  train_tag: 
  epochs: 10
  internal_epochs: 30
  enable_train: True
  learning_rate: 5e-5
  lambda_l1: 0.1
  ckpt_interval: 1
  ckpt_epoch: -1
  export_video: True
  video_interval: 1
  prompt: "a pillow on a sofa"

model:
  network: 'knn'
  normalize_features: True
  hidden_size: 768
  depth: 0
  num_heads: 8
  mlp_ratio: 2
  num_groups: 8192
  group_size: 32

material:
  center: [0.5, 0.5, 0.5]
  size: [1.0, 1.0, 1.0]
  rho: 2000.0
  elasticity_physicals:
    - 'CorotatedElasticity'
    - 'StVKElasticity'
    - 'SigmaElasticity'
    - 'VolumeElasticity'
  plasticity_physicals:
    - 'IdentityPlasticity'
    - 'DruckerPragerPlasticity'
    - 'SigmaPlasticity'
    - 'VonMisesPlasticity'
  elasticity: 'neural'
  plasticity: 'neural'
  vlm_pred_path:

render:
  white_bg: True
  mpm_space_vertical_upward_axis: [0, 0, 1]
  mpm_space_viewpoint_center: [0.5, 0.5, 0.5]
  default_camera_index: -1
  show_hint: False
  init_azimuthm: 0.0
  init_elevation: 30.0
  init_radius: 2.5
  move_camera: False
  delta_a: 0.5
  delta_e: 0.0
  delta_r: 0.0

preprocessing:
  opacity_threshold: 0.02
  rotation_degree: []
  rotation_axis: []
  sim_area: [-0.65, 0.65, -0.6, 0.6, -1, 1]
  scale_factor: 1.0
  translate_to_center: True
  particle_filling:
    n_grid: 128
    density_threshold: 40.0
    search_threshold: 0.5
    search_exclude_direction: 5
    ray_cast_direction: 0
    max_particles_num: 2000000
    max_particles_per_cell: 4
    # boundary: [0.6, 1.4, 0.6, 1.4, 0.92, 1.72]
    boundary: [0.1, 0.9, 0.1, 0.9, 0.42, 1.12]
    visualize: False
    smooth: False

sim:
  num_grids: 100
  dt: 1e-4
  gravity: [0.0, 0.0, -5.0]
  frames_per_stage: 20
  num_frames: 300
  num_skip_frames: 0
  steps_per_frame: 200
  clip_bound: 0.5
  damping: 1.0
  boundary_conditions:
    - type: 'surface_collider'
      point: [1.0, 1.0, 0.0]
      normal: [0.0, 0.0, 1.0]
      surface: 'sticky'
      friction: 0.0
      start_time: 0.0
      end_time: 1e3
    # - type: 'cuboid'
    #   # point: [1, 1, 0.5]
    #   point: [0.5, 0.5, 0.0]
    #   size: [1.0, 1.0, 0.05]
    #   velocity: [0, 0, 0]
    #   start_time: 0.0
    #   end_time: 1e3
    #   # reset: 1
    - type: 'enforce_particle_translation'
      # point: [1, 1, 0.5]
      point: [0.5, 0.5, 0.2]
      size: [1, 1, 0.2]
      velocity: [0, 0, 0]
      start_time: 0.0
      end_time: 1e3
    # - type: 'cuboid'
    #   # point: [1, 1, 1.2]
    #   point: [0.5, 0.5, 0.1]
    #   size: [1.0, 1.0, 0.12]
    #   velocity: [0, 0, 0]
    #   start_time: 0.0
    #   end_time: 0.5
    # - type: 'cuboid'
    #   # point: [1, 1, 1.45]
    #   point: [0.5, 0.5, 0.95]
    #   size: [1.0, 1.0, 0.1]
    #   velocity: [0, 0, 0]
    #   start_time: 0.0
    #   end_time: 1.0